; ============================================================
;  TANDON MONITORING - PlatformIO Project
;  1 project, 2 firmware (environment):
;    - node_sensor -> ESP32 #1, baca semua sensor fisik, kirim via LoRa (Tanpa AI)
;    - gateway     -> ESP32 #2, terima LoRa, inferensi Edge AI, kirim ke WiFi/Firebase/Telegram
; ============================================================

[platformio]
default_envs = node_sensor, gateway

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Iinclude

[env:node_sensor]
build_src_filter = +<node/*>
build_flags =
    ${env.build_flags}
    -D DEVICE_ROLE_NODE
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
lib_ignore =
    FirebaseClient
    TelegramNotifier
    OtaUpdater
    WaterQualityAI

[env:gateway]
build_src_filter = +<gateway/*>
build_flags =
    ${env.build_flags}
    -D DEVICE_ROLE_GATEWAY
    -D CURRENT_FW_VERSION=\"v1.0.2\"
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
lib_ignore =
    Sensors
    SensorCore
